#!/bin/sh
# Copyright 2010 Antoine Bertin
# <diaoulael [ignore this] at users.sourceforge period net>
#
# This file is part of syno-packager.
#
# syno-packager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# syno-packager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with syno-packager.  If not, see <http://www.gnu.org/licenses/>.

# Find the CPU architecture
synoinfo=`get_key_value /etc.defaults/synoinfo.conf unique`
arch=`echo $synoinfo | cut -d_ -f2`

preinst ()
{
	# Check if the architecture is supported
	if ! echo "$arch" | grep -q "%SPK_ARCH%"; then
		echo "Your architecture is not supported by this package. Architecture  : '$arch'. Synology info : '$synoinfo'. Required : '%SPK_ARCH%'."
		exit 1
	fi
	exit 0
}

postinst ()
{
	# Correct the files ownership
	chown -R root:root ${SYNOPKG_PKGDEST}

	# Create the view directory
	mkdir -p /usr/local/SABnzbd
	mkdir -p /usr/local/bin

	# Create symlinks to the installation ditectory
	ln -s ${SYNOPKG_PKGDEST}/bin /usr/local/SABnzbd/bin
	ln -s ${SYNOPKG_PKGDEST}/lib /usr/local/SABnzbd/lib
	ln -s ${SYNOPKG_PKGDEST}/SABnzbd /usr/local/SABnzbd/SABnzbd
	ln -s ${SYNOPKG_PKGDEST}/var /usr/local/SABnzbd/var
	ln -s ${SYNOPKG_PKGDEST}/etc /usr/local/SABnzbd/etc

	# Create symlinks
	for bin in /usr/local/SABnzbd/bin/*
	do
		ln -s $bin /usr/local/bin/`basename $bin`
	done

	# Correct the files permission
	chmod 555 /usr/local/SABnzbd/bin/*
	chmod 555 /usr/local/SABnzbd/lib/*
	chown root:users /usr/local/SABnzbd/var
	chmod 775 /usr/local/SABnzbd/var

	exit 0
}

preuninst ()
{
	exit 0
}

postuninst ()
{
	# Remove symlinks
	for bin in /usr/local/SABnzbd/bin/*
	do
		rm -f /usr/local/bin/`basename $bin`
	done

	# Remove symlinks from /usr/local/SABnzbd
	rm -f /usr/local/SABnzbd/bin
	rm -f /usr/local/SABnzbd/lib
	rm -f /usr/local/SABnzbd/SABnzbd
	rm -f /usr/local/SABnzbd/var
	rm -f /usr/local/SABnzbd/etc

	# Remove "share" folder for SABnzbd to find shared files
	rm -f /usr/local/share/SABnzbd

	# Remove the view directory
	rmdir /usr/local/SABnzbd

	exit 0
}

preupgrade ()
{
	exit 1
}

postupgrade ()
{
	exit 1
}
