#!/bin/sh
# Copyright 2009 Saravana Kannan
# <sarav dot devel [ignore this] at gmail period com>
#
# This file is part of syno-packager.
#
# syno-packager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# syno-packager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with syno-packager.  If not, see <http://www.gnu.org/licenses/>.

if [ "$1" = "" -o "$2" = "" ]; then
	echo "`basename $0` <username> <webui port> [<webui passwd>]"
	echo "<webui passwd> defaults to <username>!!!"
	exit 1
fi

pkgdir=`ls -cl $0 | sed -r "s/.*-> (.*)/\1/g"`
pkgdir=`dirname $pkgdir`

username=$1
port=$2
userpwd=$3

if [ "$userpwd" = "" ]; then
	userpwd=$username!!!
fi

configdir=`su $username -s /bin/sh -c "cd && pwd"`/.config/transmission-daemon
su $username -s /bin/sh -c "mkdir -p $configdir"

if [ ! -f $configdir/settings.json ]; then
	sed -r "s/%RPCUSERNAME%/$username/g; s/%RPCPORT%/$port/g; s/%RPCPASSWD%/$userpwd/g" /$pkgdir/settings.json > $configdir/settings.json
	chown $username:users $configdir/settings.json
else
	echo "Using preexisting user settings."
fi

echo "$username" >> /usr/local/etc/transmission.users
