#!/bin/sh
# Copyright 2009 Saravana Kannan
# <sarav dot devel [ignore this] at gmail period com>
#
# This file is part of syno-packager.
#
# syno-packager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# syno-packager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with syno-packager.  If not, see <http://www.gnu.org/licenses/>.

# Restart transmission only if it had run for atleast this many seconds.
min_run_secs=30
run_time=$min_run_secs
libdir=/var/packages/transmission/target/usr/local/lib

while [ $run_time -ge $min_run_secs ];
do
	start_time=`date +%s`
	LD_LIBRARY_PATH=$libdir transmission-daemon -f
	time=`date +%s`
	run_time=$(($time - $start_time))
	echo "Transmission ran for $run_time seconds."
done
