#!/bin/sh

start_daemon() {
	ulist=`cat /usr/local/etc/transmission.users`
	if [ "$ulist" = "" ]; then
		return 1
	fi
	for u in $ulist
	do
		su $u -s /bin/sh -c "transmission-daemon"
	done
	return 0
}

stop_daemon() {
	# Need to kill 2-3 times to work
	killall transmission-daemon
	killall transmission-daemon
	killall transmission-daemon
}

daemon_status() {
	procs=`ps -ef | grep transmission-daemon | grep -v grep`
	if [ "$procs" = "" ]; then
		echo Not running.
		exit 1
	else
		echo Running.
		exit 0
	fi
}

case $1 in
start)
	echo Starting...
	start_daemon
	daemon_status;;
stop)
	echo Stopping...
	stop_daemon
	exit 0;;
restart)
	stop_daemon
	sleep 2
	start_daemon
	daemon_status;;
status)
	# 0 - running
	# 1 - stopped
	daemon_status;;
esac

exit 1
